---
- hosts: win
  gather_facts: no
  tasks:
    - name: Download PuTTY installer
      win_get_url:
        url: "https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.80-installer.msi"
        dest: "C:\\Temp"
